INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Vinegar', '2 cups', 0);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Water', '2 cups', 0);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Dish Soap', '1 tbsp', 0);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Anise', 'Coughs, bronchitis, digestive-linked migraines and headaches', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Basil', 'smells garden-fresh, spicy and floral. It has a clarifying effect on the brain and helps with mental alertness. An uplifting oil that inspires confidence, Basil can be beneficial to healthy respiratory and digestive systems.', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Bay', ' has a spicy, balsamic scent. A mentally stimulating, invigorating oil that is often used in hair and scalp tonics. Bay can be irritating to the skin, so dilute properly before using.', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Bergamot', 'is wonderfully uplifting and refreshing with a fruity, floral scent. Its considered a tonic for frazzled nerves. Can be supportive to healthy digestive and upper respiratory systems. Often used as an air freshener to combat odors.', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Cardamom', ' is a spicy, yet sweet smelling oil. It is believed to be mentally stimulating and to help aid concentration. A support to healthy digestive and respiratory systems.', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Cedarwood', 'has a pleasing, woody aroma and has been used since antiquity for perfumery and as a preservative. Wonderful addition to a skin and hair care regime. This oil helps calm nervous tension and anxiety, and is supportive for a healthy upper respiratory system.', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Chamomile Roman', 'has a sweet, fruity odor often referred to as apple-like. Promotes an inner sense of peace and calming.  Can be supportive to healthy reproductive and digestive systems, and as a balm for muscle soreness and spasm. Excellent for skin care.', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Cinnamon', 'has a warm, spicy odor that is warming and mentally stimulating. It aids healthy digestive, respiratory and circulatory systems and is traditionally used to boost the immune system. ', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Citronella', 'has a fresh grassy, lemony scent and is commonly used to ward off insects. It also has a very calming effect on the nervous system and acts as a general tonic for the body. It is often used in skin care products to impart a fresh scent.', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Clary Sage', ' has a sweet, musky, spicy odor. A relaxing and uplifting oil that helps ease emotional stress. Supportive to a healthy digestive system and believed to help strengthen the immune system and help balance hormones. Lovely for hair care, especially the scalp.', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Clove', ' has a penetrating warm, spicy aroma that is mentally uplifting and stimulating. It helps support healthy respiratory and digestive systems and fortify the immune system. Because of its trademark reputation as a disinfectant, Clove makes a great oil to use in room sprays and aromatherapy diffusers.', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Eucalyptus globulus', 'is a sharp camphor smelling oil thats invigorating, penetrating and cleansing. Helps support healthy immune and respiratory systems.', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Fennel', ' has a sweet licorice scent. This oil is similar to Dill for its soothing action on the digestive system. Additionally, when used in a massage, it helps encourage the release of toxins.', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Fir', 'has a clean, pleasant, balsamic aroma. This oil is warming and grounding. Often used for muscular aches and is beneficial to a healthy respiratory system.', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Frankincense', ' has an earthy yet spicy scent. This oil is traditionally used for its sacred healing qualities. It is considered to slow and deepen your breathing making your mood more conducive for meditation. Can be helpful for mature and problematic skin. Supportive to healthy respiratory, digestive and reproductive systems.', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Ginger', ' root has a warm and spicy grounding aroma. A drop of oil on a tissue for inhalation can help relieve jet lag or motion sickness. It is very beneficial to digestion. It helps support healthy respiratory and circulatory systems and has a warming and soothing effect on muscles.', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Grapefruit', ' has a fresh, sweet citrus aroma that is cheerful and uplifting. Great for mental exhaustion and to help recover from jet lag. Often used to combat odors and freshen your environment. It is stimulating to the lymphatic and digestive systems.', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Jasmine', ' is a rich, warm, floral fragrance known for its aphrodisiac properties. It is calming and emotionally balancing.  Helps promote confidence and creativity. Helps support healthy reproductive and respiratory systems.', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Juniper', 'has a sweet, fresh, woody odor that is mentally stimulating. Because of its powerful detoxifying properties, it can have a rejuvenating effect on the body. Helps support muscle and joint issues as well as healthy respiratory and digestive systems. ', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Lavandin', 'is a cross of  true Lavender and Spike Lavender.  This hybrid has Lavenders familiar sweet floral scent but with a hint of camphor. Its uses and benefits are similar to Lavender. ', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Lavender', ' has a light, sweet floral scent. The variety from France (L. angustifolium) has a softer, more complex scent than the one from Bulgaria (L. vera), but shares many of the same properties. Undeniably the most popular oil for all age groups, it is therapeutically superior for many conditions (from sleeplessness to stress) and definitely the number one choice for first aid. Supportive to healthy reproductive, respiratory, lymphatic and immune systems. Great for skin.', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Lemon', ' has a light, fresh citrus scent. This oil is uplifting, energizing and promotes optimism. Great to add to household cleaners. It helps support healthy immune, circulatory and digestive systems.', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Lemongrass', 'has a penetrating lemony herbaceous scent. This oil has a soothing effect on the emotions. Provides support to healthy immune and circulatory systems.', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Mandarin', 'has a sweet, floral citrus scent that helps ease anxiety, nervous tension and irritability. It is uplifting and revitalizing. Helps support a healthy digestive system. Often used as an air freshener to combat odors.', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Myrrh', ' has a penetrating, smoky, musky aroma. It helps support healthy immune and digestive systems. Use as a chest balm or inhalation to help support a healthy respiratory system. Combined with Frankincense, it has an even more powerful effect. Both oils are used to help facilitate meditation.', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Niaouli', 'smells like Eucalyptus (clearing and penetrating) but has properties similar to Tea Tree. It is mentally stimulating and helps concentration. Its gentle action is beneficial to healthy respiratory, digestive and circulatory systems and can be used for a variety of skin issues.', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Orange', ' is sweet, fresh and fruity smelling. This oil helps alleviate tension and stress and promotes a positive outlook. It is considered relaxing, uplifting and refreshing. Wonderful as an air freshener to combat odors and freshen your rooms. Helps support healthy digestive and immune systems.', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Oregano', 'has a warm, spicy herbaceous odor. It is mentally stimulating, relaxing to muscular strains and beneficial for a healthy upper respiratory system. CAUTION: This oil can be irritating to the skin and mucous membranes. It should be diluted to no more than 1% and first tested on a small patch of skin.', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Patchouli', 'has a sweet, rich, earthy aroma that is mentally grounding and balancing. Great for skin care in addition to supporting healthy digestive and immune systems.', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Peppermint', ' has a penetrating grassy, mint scent thats mentally stimulating and useful in soothing nervous stress. It helps relieve common muscular aches and pains; however, this oil can quickly drop the body temperature because of its menthol content so use it well diluted and only on small, localized areas of the body. Helps fortify healthy immune, digestive and circulatory systems. Known to deter mice, ants and spiders.', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Pine', ' with its clean, forest fragrance is mentally refreshing. It is excellent support  for a healthy upper respiratory system and helps stimulate circulation. Use this oil to rid your home of unwanted smells. Also a great car deodorizer!', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Rose', 'has an exquisite, rich floral fragrance that helps relieve stress and nervous tension and promote positive feelings. It is excellent for skin care but particularly for mature, dry or sensitive skin. Beneficial to healthy reproductive, circulatory and digestive systems. It is considered precious oil because it takes large amounts of rose petals to produce small amounts of the oil.', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Rosemary', 'has a strong, fresh, herbaceous aroma. Its stimulating effect on the brain is good for tasks where alertness, memory recall and being mentally sharp are required. Combine with basil for an enhanced effect. It also helps soothe tired muscles, fortifies healthy immune and respiratory systems, as well as being a stimulant for the circulatory system.', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Sandalwood', ' has an exotic, soft, woody scent. It has a calming influence on the mind and emotions. It is very useful in skin care, especially dry skin. Popular since antiquity, it was used to help boost the immune system and is beneficial to the respiratory system. Sandalwood is an endangered species. Wyndmere purchases only AG marked oil from plantations that practice reforestation and is approved for exportation by the Indian government.', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Spearmint', ' has a sweet minty aroma which can be mentally stimulating. Wonderful for its cooling properties, its also traditionally used to aid the digestive system and for jet lag. Its properties are similar to Peppermint but more gentle.', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Tangerine', ' is very sweet, floral citrus scent thats uplifting and stress relieving. This oil is often used as an air freshener to combat odors. Combine with a Lavender to achieve a relaxing and cheerful effect. It is beneficial to a healthy digestive system and helps stimulate circulation.', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Tea Tree', ' has a fresh, spicy camphor scent that is cleansing and revitalizing. It helps boost a healthy immune system and is good for skin care as well as being an effective first aid oil. Reputed to be effective against nail bed fungus. Also traditionally used for controlling mold by diffusing in the affected area or adding to household cleaners.', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Thyme', ' is a stimulating oil with a strong, woody, spicy aroma that helps sharpen concentration. This is a wonderful oil to help strengthen a healthy immune system. In addition, it is beneficial to healthy respiratory, circulatory and digestive systems. It also helps clean the air when used as an air freshener.', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Vetiver', 'has a rich, smoky, earthy aroma thats deeply relaxing and grounding. Its very calming in stressful situations and promotes meditation. Traditionally used for soothing muscular aches and pains and is beneficial to a healthy reproductive system. Good for oily skin. This oil improves with age.', 1);
INSERT INTO Ingredients (Name, Description, IsOil) VALUES ('Ylang Ylang', ' has an intensely sweet and floral fragrance. Believed to help assuage fears and feelings of stress and anxiety, it has a very calming effect and may help with melancholy.  Its thought to have a balancing effect on sebum which makes it good for both oily and dry skin', 1);

INSERT INTO RecipeType (Name) VALUES ('Cleaner');
INSERT INTO RecipeType (Name) VALUES ('Diffuser');
INSERT INTO RecipeType (Name) VALUES ('Medicinal');
INSERT INTO RecipeType (Name) VALUES ('Perfume');

SELECT * FROM RecipeType;

SELECT * FROM FavoriteRecipes;

SELECT * FROM RecipeIngredients;

SELECT * FROM Ingredients;
